# Generated by Django 4.2.3 on 2023-07-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cand_ans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('q_id', models.IntegerField()),
                ('ques', models.TextField()),
                ('ans', models.TextField()),
                ('keywords_ans', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('username', models.CharField(max_length=122, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=9)),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ques_ans',
            fields=[
                ('qa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ques', models.TextField()),
                ('ans', models.TextField(default=['x', 'y', 'z'], null=True)),
            ],
        ),
    ]
