# Generated by Django 4.2.3 on 2023-08-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cand_bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('q_id', models.IntegerField()),
                ('ques', models.TextField()),
                ('ans', models.TextField()),
                ('keywords_ans', models.TextField(null=True)),
            ],
        ),
    ]
