# Generated by Django 4.2.3 on 2023-08-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cand_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='cand_bank',
            name='user',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
